---
- name: pgdg yum key
  copy:
    src: RPM-GPG-KEY-PGDG
    dest: "{{ pgdg_yum_key_path }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - import pgdg rpm key
  when: ansible_distribution == 'CentOS'

- name: pgdg yum repo
  yum_repository:
    state: present
    name: "pgdg{{ postgres_short_version }}"
    baseurl: "{{ pgdg_yum_base_url }}/{{ postgres_version }}/redhat/rhel-$releasever-$basearch"
    description: "PostgreSQL {{ postgres_version }} $release - $basearch"
    enabled: yes
    file: "{{ pgdg_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "{{ pgdg_yum_key_path }}"
  when: ansible_distribution == 'CentOS'

- name: pgdg yum source repo
  yum_repository:
    state: present
    name: "pgdg{{ postgres_short_version }}-source"
    baseurl: "{{ pgdg_yum_base_url }}/srpms/{{ postgres_version }}/redhat/rhel-$releasever-$basearch"
    description: "PostgreSQL {{ postgres_version }} $release - $basearch - Source"
    enabled: no
    file: "{{ pgdg_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "{{ pgdg_yum_key_path }}"
  when: ansible_distribution == 'CentOS'

- name: pgdg apt key
  copy:
    src: "{{ pgdg_apt_key }}"
    dest: "{{ pgdg_apt_key_path }}"
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'Ubuntu'

- name: pgdg apt source list
  apt_repository:
    state: present
    repo: "deb {{ pgdg_apt_base_url }} {{ ansible_distribution_release }}-pgdg main"
    filename: pgdg
    mode: '0644'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
