---
oracle_cache_dir: /var/cache/oracle
oracle_jdk_state: present

# Dictionary for information about the various Oracle JDK releases.
#
# * JDK Release version
#   * JDK Release version update
#     * Build
#     * CDN Hash (to prevent automatic downloads)
#     * SHA256 checksums, keyed by package type.
oracle_jdk_data:
  8:
    131:
      build: '11'
      hash: 'd54c1d3a095b4ff2b6607d096fa80163'
      checksums:
        rpm: '3d1e8cc66f4fd77acef6093329d5dd95bd06e4a03926c52df794f311a0c093f8'
        tar.gz: '62b215bdfb48bace523723cdbb2157c665e6a25429c73828a32f00e587301236'
    144:
      build: '01'
      hash: '090f390dda5b47b9b721c7dfaa008135'
      checksums:
        rpm: 'cdb016da0c509d7414ee3f0c15b2dae5092d9a77edf7915be4386d5127e8092f'
        tar.gz: 'e8a341ce566f32c3d06f6d0f0eeea9a0f434f538d22af949ae58bc86f2eeaae4'
    151:
      build: '12'
      hash: 'e758a0de34e24606bca991d704f6dcbf'
      checksums:
        rpm: '2c1137859aecc0a6aef8960d11967797466e9b812f8c170a43a2597e97dc8a08'
        tar.gz: 'c78200ce409367b296ec39be4427f020e2c585470c4eed01021feada576f027f'
    152:
      build: '16'
      hash: 'aa0333dd3019491ca4f6ddbe78cdb6d0'
      checksums:
        rpm: 'b95c69b10e41d0f91e1ae6ef51086025535a43235858326a5a8fd9c5693ecc28'
        tar.gz: '218b3b340c3f6d05d940b817d0270dfe0cfd657a636bad074dcabe0c111961bf'

# All of these variables are necessary to construct a download URL, as Oracle uses the folllowing:
#  * The JDK release major version, update version, and the build version.
#  * An arbitrary hash to prevent automatic URL usage on new releases.
#  * The package type (currently rpm and tar.gz are supported).
oracle_jdk_release: "{{ oracle_jdk_version }}u{{ oracle_jdk_update }}-b{{ oracle_jdk_data[oracle_jdk_version][oracle_jdk_update].build }}"
oracle_jdk_base_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_jdk_release }}/{{ oracle_jdk_data[oracle_jdk_version][oracle_jdk_update].hash }}"
oracle_jdk_basename: "jdk-{{ oracle_jdk_version }}u{{ oracle_jdk_update }}-linux-x64.{{ oracle_jdk_package_type }}"
oracle_jdk_download_url: "{{ oracle_jdk_base_url }}/{{ oracle_jdk_basename }}"

# Pull out the expected checksum for verification and construct the file destination
# for the `get_url` module.
oracle_jdk_checksum: "{{ oracle_jdk_data[oracle_jdk_version][oracle_jdk_update]['checksums'][oracle_jdk_package_type] }}"
oracle_jdk_file: "{{ oracle_cache_dir }}/{{ oracle_jdk_basename }}"
