---
- name: nodesource yum key
  copy:
    src: "{{ nodesource_yum_key }}"
    dest: "{{ nodesource_yum_key_path }}"
    owner: root
    group: root
    mode: '0644'

- name: nodesource yum repo
  yum_repository:
    state: present
    name: nodesource
    baseurl: "{{ nodesource_yum_base_url }}/$releasever/$basearch"
    description: "Node.js Packages for Enterprise Linux $releasever - $basearch"
    enabled: yes
    failovermethod: priority
    file: "{{ nodesource_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "file://{{ nodesource_yum_key_path }}"

- name: nodesource yum source repo
  yum_repository:
    state: present
    name: nodesource-source
    baseurl: "{{ nodesource_yum_base_url }}/$releasever/SRPMS"
    description: "Node.js Packages for Enterprise Linux $releasever - $basearch"
    enabled: no
    failovermethod: priority
    file: "{{ nodesource_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "file://{{ nodesource_yum_key_path }}"
