---
- name: include nodejs variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: setup nodesource repo
  include_tasks: "{{ ansible_distribution }}.yml"

- name: nodejs package
  package:
    name: "{{ nodejs_package }}"
    state: "{{ nodejs_package_state }}"

- name: nodejs development package
  package:
    name: "{{ nodejs_devel_package }}"
    state: "{{ nodejs_devel_package_state }}"
  when: nodejs_devel_package is defined

- name: nodejs version lock
  include_tasks: yum_versionlock.yml
  when: ansible_distribution == 'CentOS'
