---
- name: nodejs package
  package:
    name: "{{ nodejs_package }}"
    state: "{{ nodejs_package_state }}"

- name: nodejs development package
  package:
    name: "{{ nodejs_devel_package }}"
    state: "{{ nodejs_devel_package_state }}"

- name: nodejs yum versionlock list
  command: yum versionlock list
  register: nodejs_yum_versionlock
  when: ansible_distribution == 'CentOS'

- name: nodejs package yum versionlock
  command: "yum versionlock {{ nodejs_package }}"
  when:
    - ansible_distribution == 'CentOS'
    - nodejs_package_state == 'present'
    - nodejs_yum_versionlock.stdout.find(nodejs_package) == -1

- name: nodejs development package yum versionlock
  command: "yum versionlock {{ nodejs_devel_package }}"
  when:
    - ansible_distribution == 'CentOS'
    - nodejs_package_state == 'present'
    - nodejs_yum_versionlock.stdout.find(nodejs_devel_package) == -1
