---
- name: nodesource apt key
  copy:
    src: "{{ nodesource_apt_key }}"
    dest: "{{ nodesource_apt_key_path }}"
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'Ubuntu'

- name: nodesource apt source list
  apt_repository:
    state: present
    repo: "deb {{ nodesource_apt_base_url }} {{ ansible_distribution_release }} main"
    filename: nodesource
    mode: '0644'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
