---
- name: nodesource yum key
  copy:
    src: "{{ nodesource_yum_key }}"
    dest: "{{ nodesource_yum_key_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: import nodesource rpm key
  when: ansible_distribution == 'CentOS'

- name: nodesource yum repo
  yum_repository:
    state: present
    name: nodesource
    baseurl: "{{ nodesource_yum_base_url }}/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}"
    description: "Node.js Packages for Enterprise Linux {{ ansible_distribution_major_version }} - {{ ansible_architecture }}"
    enabled: yes
    failovermethod: priority
    file: "{{ nodesource_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "{{ nodesource_yum_key_path }}"
  when: ansible_distribution == 'CentOS'

- name: nodesource yum source repo
  yum_repository:
    state: present
    name: nodesource-source
    baseurl: "{{ nodesource_yum_base_url }}/{{ ansible_distribution_major_version }}/SRPMS"
    description: "Node.js Packages for Enterprise Linux {{ ansible_distribution_major_version }} - {{ ansible_architecture }}"
    enabled: no
    failovermethod: priority
    file: "{{ nodesource_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "{{ nodesource_yum_key_path }}"
  when: ansible_distribution == 'CentOS'

- name: nodesource apt key
  copy:
    src: "{{ nodesource_apt_key }}"
    dest: "{{ nodesource_apt_key_path }}"
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'Ubuntu'

- name: nodesource apt source list
  apt_repository:
    state: present
    repo: "deb {{ nodesource_apt_base_url }} {{ ansible_distribution_release }} main"
    filename: nodesource
    mode: '0644'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
