---
chrome_package: 'google-chrome-stable'
chrome_state: present
chrome_base_url: 'http://dl.google.com/linux/chrome'

chrome_apt_url: "{{ chrome_base_url }}/deb/"
chrome_apt_key: "/etc/apt/trusted.gpg.d/google-chrome.gpg"

chrome_yum_url: "{{ chrome_base_url }}/rpm/stable/"
chrome_yum_key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-Google-Chrome"
chrome_yum_repo: "/etc/yum.repos.d/google-chrome.repo"
