---
- name: chrome apt key
  copy:
    src: "{{ chrome_apt_key | basename }}"
    dest: "{{ chrome_apt_key }}"
    owner: root
    group: root
    mode: '0644'

- name: chrome apt source list
  apt_repository:
    state: "{{ chrome_state }}"
    repo: "deb [arch=amd64] {{ chrome_apt_url }} stable main"
    filename: google-chrome
    mode: '0644'
    update_cache: yes

- name: create xdg-icon-resource directory
  file:
    state: directory
    path: /usr/share/icons/hicolor
    owner: root
    group: root
    mode: '0755'
