---
- name: include oracle jdk vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: oracle jdk cache directory
  file:
    path: "{{ oracle_cache_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: download oracle jdk
  get_url:
    url: "{{ oracle_jdk8_download_url }}"
    dest: "{{ oracle_cache_dir }}/{{ oracle_jdk8_download_url | basename }}"
    checksum: "sha256:{{ oracle_jdk8_checksums[oracle_jdk8_update] }}"
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
