---
- name: include oracle jdk vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: oracle jdk cache directory
  file:
    path: "{{ oracle_cache_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: download oracle jdk
  get_url:
    url: "{{ oracle_jdk_download_url }}"
    dest: "{{ oracle_jdk_file }}"
    checksum: "sha256:{{ oracle_jdk_checksum }}"
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'

- name: include oracle jdk package tasks
  include_tasks: "{{ ansible_distribution }}.yml"
