---
- name: create oracle jdk home
  file:
    path: "{{ oracle_jdk_home }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: oracle_jdk_state == 'present'

- name: extract oracle jdk tar
  command: "tar --strip-components 1 -xzf {{ oracle_jdk_file }}"
  args:
    chdir: "{{ oracle_jdk_home }}"
    creates: "{{ oracle_jdk_home }}/bin/javac"
  when: oracle_jdk_state == 'present'

# Ignore Ansible warnings about using unarchive, as it doesn't work;
# keeping around as a hopeful example.
# - unarchive:
#    remote_src: yes
#    src: "{{ oracle_jdk_file }}"
#    dest: "{{ oracle_jdk_home }}"
#    extra_opts: '--strip-components 1'
#    creates: "{{ oracle_jdk_home }}/bin/javac"
#  when: oracle_jdk_state == 'present'
