---
hoot_packages:
  - asciidoc
  - autoconf
  - automake
  - bc
  - boost-devel
  - bzip2
  - ccache
  - cmake
  - cppunit-devel
  - dblatex
  - doxygen
  - gcc
  - gcc-c++
  - gdb
  - geos
  - geos-devel
  - git
  - git-core
  - glpk
  - glpk-devel
  - gnuplot
  - htop
  - libicu-devel
  - libpng-devel
  - libtool
  - m4
  - maven
  - mlocate
  - opencv
  - opencv-core
  - opencv-devel
  - opencv-python
  - perl-XML-LibXML
  - proj
  - proj-devel
  - protobuf
  - protobuf-compiler
  - protobuf-devel
  - python 
  - python-devel
  - python-matplotlib
  - python-pip 
  - python-setuptools
  - qt
  - qt-devel
  - qt-postgresql
  - qtwebkit
  - qtwebkit-devel
  - swig
  - tex-fonts-hebrew
  - texlive
  - texlive-collection-fontsrecommended
  - unzip
  - v8-devel
  - vim
  - w3m
  - wget
  - words
  - xorg-x11-server-Xvfb
  - zip
