---
hoot_packages:
  - asciidoc
  - automake
  - ccache
  - curl
  - doxygen
  - g++
  - gdb
  - git
  - git-core
  - gnuplot
  - graphviz
  - htop
  - lcov
  - libboost-all-dev
  - libboost-dev
  - libcppunit-dev
  - libcv-dev
  - libgdal-dev
  - libgeos++-dev
  - libglpk-dev
  - libicu-dev
  - liblog4cxx10-dev
  - libnewmat10-dev
  - libogdi3.2-dev
  - libopencv-dev
  - libproj-dev
  - libprotobuf-dev
  - libqt4-dev
  - libqt4-sql-psql
  - libqt4-sql-sqlite
  - libstxxl-dev
  - maven
  - npm
  - openssh-server
  - patch
  - pgadmin3
  - protobuf-compiler
  - python
  - python-dev
  - python-matplotlib
  - python-pip
  - python-setuptools
  - ruby
  - ruby-dev
  - source-highlight
  - swig
  - texinfo
  - unzip
  - w3m
  - x11vnc
  - xsltproc
  - xvfb
  - zlib1g-dev
