---
- name: pgdg yum key
  copy:
    src: RPM-GPG-KEY-PGDG
    dest: "{{ pgdg_yum_key_path }}"
    owner: root
    group: root
    mode: '0644'

- name: pgdg yum repo
  yum_repository:
    state: present
    name: "pgdg{{ postgres_short_version }}"
    baseurl: "{{ pgdg_yum_base_url }}/{{ postgres_short_version }}/redhat/rhel-$releasever-$basearch"
    description: "PostgreSQL {{ postgres_short_version }} $release - $basearch"
    enabled: yes
    file: "{{ pgdg_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "file://{{ pgdg_yum_key_path }}"

- name: pgdg yum source repo
  yum_repository:
    state: present
    name: "pgdg{{ postgres_short_version }}-source"
    baseurl: "{{ pgdg_yum_base_url }}/srpms/{{ postgres_short_version }}/redhat/rhel-$releasever-$basearch"
    description: "PostgreSQL {{ postgres_short_version }} $release - $basearch - Source"
    enabled: no
    file: "{{ pgdg_yum_repo_path }}"
    gpgcheck: yes
    gpgkey: "file://{{ pgdg_yum_key_path }}"

- name: install postgres packages
  yum:
    name: "{{ item }}"
    state: "{{ postgres_state }}"
  with_items: "{{ postgres_packages }}"

- name: install postgis packages
  yum:
    name: "{{ item }}"
    state: "{{ postgis_state }}"
  with_items: "{{ postgis_packages }}"
