---
- name: include postgres variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: install pgdg repo and packages
  include_tasks: "{{ ansible_distribution }}.yml"
