---
- name: include postgres variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: setup pgdg repo
  include_tasks: "{{ ansible_distribution }}.yml"

- name: install postgres packages
  package:
    name: "{{ item }}"
    state: "{{ postgres_state }}"
  with_items: "{{ postgres_packages }}"
