---
- name: pgdg apt key
  copy:
    src: "{{ pgdg_apt_key }}"
    dest: "{{ pgdg_apt_key_path }}"
    owner: root
    group: root
    mode: '0644'

- name: pgdg apt source list
  apt_repository:
    state: present
    repo: "deb {{ pgdg_apt_base_url }} {{ ansible_distribution_release }}-pgdg main"
    filename: pgdg
    mode: '0644'
    update_cache: yes

- name: install postgres packages
  apt:
    name: "{{ item }}"
    state: "{{ postgres_state }}"
  with_items: "{{ postgres_packages }}"

- name: install postgis packages
  apt:
    name: "{{ item }}"
    state: "{{ postgis_state }}"
  with_items: "{{ postgis_packages }}"
