---
- name: osmosis source directory
  file:
    path: "{{ osmosis_src_dir }}"
    state: directory
    owner: "{{ osmosis_user }}"
    group: "{{ osmosis_group }}"
    mode: '0755'

- name: download osmosis
  get_url:
    url: "{{ osmosis_download_url }}"
    dest: "{{ osmosis_file }}"
    owner: "{{ osmosis_user }}"
    group: "{{ osmosis_group }}"
    mode: '0644'

- name: extract osmosis
  unarchive:
    src: "{{ osmosis_file }}"
    dest: "{{ osmosis_src_dir }}"
    owner: "{{ osmosis_user }}"
    group: "{{ osmosis_group }}"
    remote_src: yes
    creates: "{{ osmosis_src_dir }}/bin/osmosis"

- name: create osmosis symlink
  file:
    state: link
    path: "{{ osmosis_bin }}"
    src: "{{ osmosis_src_dir }}/bin/osmosis"
    owner: "{{ osmosis_user }}"
    group: "{{ osmosis_group }}"
